/* Number of total semesters: */
window.semesters = 10;

/* List of available colors to toggle a course as completed */
/* The first color is default for selecting options as well, so make sure to choose that one wisely */
window.colors = ["#b1fca4", "#fac6ff", "#a8c9ff", "#ff6347", "#9400d3", "#19dfda", "#ff7373", "#223bf6"];


window.courses = [
    [
    { name: "Biologia Molecular", credits: 1, code: "BMH126", semester: 1},
    { name: "Embriologia", credits: 1, code: "BMH127", semester: 1},
    { name: "Bioquímica I", credits: 3, code: "BQM101", semester: 1},
    { name: "ICF", credits: 2, code: "FFC111", semester: 1},
    { name: "Metodologia Científica", credits: 2, code: "FFP111", semester: 1},
    { name: "Biofísica", credits: 3, code: "FFW112", semester: 1, corequirements: [1]},
    { name: "Química Geral I", credits: 4, code: "IQG114", semester: 1},
    { name: "Cálculo p/ Farmácia", credits: 3, code: "MAC108", semester: 1},
    { name: "PCI I ", credits: 8, code: "BMW203", semester: 2, requirements: [0, 2]},
    { name: "Bioquímica II", credits: 4, code: "BQM103", semester: 2, requirements: [2]},
    { name: "Química Geral II", credits: 3, code: "IQG127", semester: 2, requirements: [6]},
    { name: "Química Orgânica I", credits: 4, code: "IQO120", semester: 2, requirements: [6]},
    { name: "Bioestatística", credits: 3, code: "MAD237", semester: 2},
    { name: "Atividades Acad. Optativas", credits: 2, semester: 2},
    { name: "PCI II", credits: 11, code: "BMW204", semester: 3, requirements: [8]},
    { name: "Química Analítica I", credits: 2, code: "IQA123", semester: 3, requirements: [6], corequirements: [16]},
    { name: "Química Analítica Exp. I", credits: 2, code: "IQA124", semester: 3, requirements: [6], corequirements: [15]},
    { name: "Físico-Química ", credits: 4, code: "IQF235", semester: 3, requirements:[7]},
    { name: "Química Orgânica II", credits: 3, code: "IQO230", semester: 3, requirements:[11]},
    { name: "Química Orgânica Exp. I", credits: 2, code: "IQO242", semester: 3, requirements: [10, 11]},
    { name: "Farmacobotânica", credits: 3, code: "FFP600", semester: 4},
    { name: "Iniciacao Científica", credits: 2, code: "FFP111", semester: 4, requirements: [4]},
    { name: "Química Analítica II", credits: 2,code: "IQA233", semester: 4, requirements: [15, 16], corequirements: [23]},
    { name: "Química Analítica Exp. II", credits: 2, code: "IQA234", semester: 4, requirements: [15, 16], corequirements: [22]},
    { name: "Bioinorgânica", credits: 4, code: "IQG234", semester: 4, requirements: [10]},
    { name: "Métodos Espectrométricos", credits: 3, code: "IQO220", semester: 4, requirements: [18, 19]},
    { name: "Química Orgânica III", credits: 3, code: "IQO240", semester: 4, requirements: [18]},
    { name: "Atividades Acad. Optativas", credits: 3, semester: 4},
    { name: "Farmacocinética e Farmacodinâmica", credits: 2, code: "BMF310", semester: 5, requirements: [9, 14]},
    { name: "Saúde Coletiva", credits: 2, code: "FFC303", semester: 5},
    { name: "Análises Farmacêuticas", credits: 5, code: "FFM302", semester: 5, requirements: [17, 22, 23]},
    { name: "Política de Saúde", credits: 2, code: "FFM311", semester: 5},
    { name: "Microbiologia e Imunologia", credits: 8, code: "IMW360", semester: 5, requirements: [2]},
    { name: "Química Orgânica Exp. II", credits: 2, code: "IQO251", semester: 5, requirements: [19, 25, 26]},
    { name: "Atividades Acad. Optativas", credits: 2, semester: 5},
    { name: "Farmacologia Neuroendócrina", credits: 4, code: "BFM320", semester:6, requirements: [14, 28]},
    { name: "Parasitologia", credits: 3, code: "CFP215", semester: 6, requirements: [14, 32]},
    { name: "Micro Imuno Clínica", credits: 3, code: "FFC480", semester: 6, requirements: [32]},
    { name: "Metabolismo Integrado", credits: 4, code: "FFI311", semester: 6, requirements: [9]},
    { name: "Farmacotécnica I", credits: 4, code: "FFM313", semester: 6, requirements: [28]},
    { name: "Farmacognosia I", credits: 3, code: "FFP313", semester: 6, requirements: [20, 26]},
    { name: "Química de Alimentos", credits: 3, code: "FFP324", semester: 6, requirements: [9, 22]},
    { name: "Farmacologia Cardio/Quimio", credits: 4, code: "BMF410", semester: 7, requirements: [14, 35]},
    { name: "Bioquímica Clínica", credits: 3, code: "FFC304", semester: 7, requirements: [9, 14]},
    { name: "Diagnóstico Clínico Laboratorial", credits: 2, code: "FFC321", semester: 7, requirements: [32, 36]},
    { name: "Hematologia", credits: 2, code: "FFC322", semester:7, requirements: [14]},
    { name: "Farmacotécnica II", credits: 4, code: "FFM323", semester: 7, requirements: [39]},
    { name: "Assist. e Atenção Farm.", credits: 2, code: "FFM481", semester: 7, requirements: [35, 39]},
    { name: "Estágio Sup. Farm. Comun.", credits: 2, code: "FFM481", semester: 7, requirements: [28, 39]},
    { name: "Farmacognosia II", credits: 3, code: "FFP323", semester: 7, requirements: [40]},
    { name: "Análises de Alimentos", credits: 3, code: "FFP403", semester: 7, requirements: [41]},
    { name: "Parasitologia e Micologia Clínica", credits: 3, code: "FFC406", semester: 8, requirements: [36]},
    { name: "Química Farm. Med.", credits: 5, code: "FFI401", semester: 8, requirements: [26, 42]},
    { name: "Farmácia Hospitalar", credits: 2, code: "FFM300", semester: 8, corequirements: [42, 46]},
    { name: "Deonto. e Legisl. Farmacêutica", credits: 2, code: "FFM301", semester: 8},
    { name: "Farmaco-epidemiologia", credits: 2, code: "FFM402", semester: 8, requirements: [12, 29]},
    { name: "Farmacotécnica Hospitalar", credits: 2, code: "FFM403", semester: 8, requirements: [46], corequirements: [53]},
    { name: "Tecnologia Ind. Farm.", credits: 4, code: "FFM408", semester: 8, requirements: [10, 39]},
    { name: "Estág. Sup. Farm. Manip. Alopática", credits: 2, code: "FFMU07", semester: 8, corequirements: [42, 46]},
    { name: "Bromatologia em Saúde", credits: 3, code: "FFP402", semester: 8, requirements: [41]},
    { name: "Atividades Acad. Livre. Esc.", credits: 2, semester: 8},
    { name: "Atividades Acad. Optativas", credits: 2, semester: 8},
    { name: "Toxicologia Geral", credits: 3, code: "FFC314", semester: 9, requirements:[26, 28]},
    { name: "Con. Bio. Micro. Quali. Pro. Farma.", credits: 4, code: "FFI402", semester: 9, requirements:[28, 32]},
    { name: "Biofarmácia", credits: 2, code: "FFM405", semester: 9, requirements: [46]},
    { name: "Dermocosméticos", credits: 2, code: "FFM406", semester: 9, requirements: [39]},
    { name: "Biotecnologia Farmacêutica", credits: 3, code: "FFM426", semester: 9, requirements: [32, 38]},
    { name: "Estágio Sup. Farmácia Hosp.", credits: 2, code: "FFMU08", semester: 9, requirements: [42, 46, 53]},
    { name: "TCC", credits: 0, code: "FFWK02", semester: 9, requirements: [21]},
    { name: "Economia e Adm, Empr. Farm.", credits: 3, code: "IEEE326", semester: 9},
    { name: "Atividades Acad. Livre. Esc.", credits: 3, semester: 9},
    { name: "Atividades Acad. Optativas", credits: 6, semester: 9, step: 1},
    { name: "Estágio Sup Especialidades", credits:8, code: "FFWU06", semester: 10},
    ],
    [
    { name: "Int. à Eng. Controle e Automação", credits: 2, code: "COE100", semester: 1, category: 1},
    { name: "Algoritmos e Programação", credits: 5, code: "COS110", semester: 1, category: 1},
    { name: "Lógica Matemática", credits: 5, code: "COS230", semester: 1},
    { name: "Física Experimental I", credits: 1, code: "FIS111", semester: 1, category: 1},
    { name: "Física I", credits: 4, code: "FIT112", semester: 1},
    { name: "Química EE", credits: 4, semester: 1, code: "IQG111", category: 1},
    { name: "Cálculo I", credits: 6, code: "MAC118", semester: 1},
    { name: "Sistemas Projetivos", credits: 5, code: "EEG105", semester: 2},
    { name: "Circuitos Lógicos", credits: 5, code: "EEL280", semester: 2},
    { name: "Linguagens de Programação", credits: 5, code: "EEL670", semester: 2, category: 1},
    { name: "Física Experimental II", credits: 1, code: "FIS121", semester: 2, requirements: [3, 4], category: 1},
    { name: "Física II", credits: 4, code: "FIT122", semester: 2, requirements: [4, 6], category: 1},
    { name: "Cálculo II", credits: 4, code: "MAC128", semester: 2, requirements: [6], category: 1},
    { name: "Mecânica I", credits: 5, code: "EEA212", semester: 3, requirements: [12], category: 1},
    { name: "Mét. Mat. em Eng. Eletrônica", credits: 4, code: "EEI356", semester: 3, requirements: [12], category: 1},
    { name: "Física III", credits: 4, code: "FIM230", semester: 3, requirements: [12], category: 1},
    { name: "Física Experimental III", credits: 1, code: "FIN231", semester: 3, requirements: [10], category: 1},
    { name: "Cálculo III", credits: 4, code: "MAC238", semester: 3, requirements: [12], category: 1},
    { name: "Álgebra Linear II", credits: 4, code: "MAE125", semester: 3, category: 1},
    { name: "Atividades Acad. Opt. (Grupo 1)", credits: 2, semester: 3, category: 4},
    { name: "Estatística e Mod. Probabilísticos", credits: 4, code: "COE241", semester: 4, category: 1},
    { name: "Sinais e Sistemas", credits: 4, code: "COE350", semester: 4, category: 1},
    { name: "Circuitos Elétricos em CC", credits: 4, code: "EEE321", semester: 4, requirements: [12, 15], category: 1},
    { name: "Sistemas Digitais", credits: 5, code: "EEL480", semester: 4, requirements: [8], category: 1},
    { name: "Física IV", credits: 4, code: "FIM240", semester: 4, requirements: [15], category: 1},
    { name: "Física Experimental IV", credits: 1, code: "FIN241", semester: 4, requirements: [16], category: 1},
    { name: "Matemática Computacional", credits: 4, code: "COC351", requirements: [6, 18], semester: 5, category: 1},
    { name: "Modelagem de Sistemas Dinâmicos", credits: 4, code: "COE240", requirements: [21], semester: 5, category: 1},
    { name: "Processos de Fabricação", credits: 4, code: "COM352", semester: 5, category: 1},
    { name: "Lab. Circuitos Elétricos I", credits: 5, code: "EEE322", requirements: [22], semester: 5, category: 1},
    { name: "Engenharia e Meio Ambiente", credits: 2, code: "EEH210", semester: 5, category: 1},
    { name: "Eletrônica I", credits: 2, code: "EEL338", requirements: [22], semester: 5, category: 1},
    { name: "Controle Realimentado", credits: 4, semester: 6, code: "COE360", requirements: [21, 26], category: 1},
    { name: "Introdução à Otimização", credits: 4, semester: 6, code: "COM361", requirements: [17], category: 1},
    { name: "Lab. Eletrônica I", credits: 4, code: "EEL339", requirements: [29, 31], semester: 6, category: 1},
    { name: "Eletrônica II", credits: 4, code: "EEL438", requirements: [31], semester: 6, category: 1},
    { name: "Redes de Computadores I", credits: 4, code: "EEL878", semester: 6, category: 1},
    { name: "Controle e Inst. de Processos", credits: 4, code: "EQE487", semester: 6, category: 1},
    { name: "Controle Avançado", credits: 4, code: "COE470", requirements: [32], semester: 7, category: 1},
    { name: "Sensores e Atuadores I", credits: 3, code: "COE471", requirements: [31], semester: 7, category: 1},
    { name: "Planej. de Proc. e Fabric. Ind.", credits: 4, code: "COP473", semester: 7, category: 1},
    { name: "Automação Industrial", credits: 4, code: "EEE643", requirements: [32], semester: 7, category: 1},
    { name: "Lab. Eletrônica II", credits: 4, code: "EEL439", requirements: [34, 35], semester: 7, category: 1},
    { name: "Processamento de Sinais", credits: 4, code: "EEL711", requirements: [21, 27], semester: 7, category: 1},
    { name: "Planej. e Aval. de Projetos", credits: 8, code: "EQE486", semester: 7, step: 1, category: 2},
    { name: "Controle em Tempo Real", credits: 4, code: "COE480", requirements: [32], semester: 8, category: 1},
    { name: "Sensores e Atuadores II", credits: 4, code: "COE481", requirements: [22], semester: 8, category: 1},
    { name: "Lab. de Automação e Controle", credits: 4, code: "COE482", requirements: [32], semester: 8, category: 1},
    { name: "Robótica e Automação", credits: 4, code: "EEL855", requirements: [32], semester: 8, category: 1},
    { name: "Sist. de Controle Não Lineares", credits: 4, code: "EEL856", requirements: [32], semester: 8, category: 1},
    { name: "Inst. Automação Ind. de Processo", credits: 4, code: "EQE026", semester: 8, category: 1},
    { name: "Engenharia de Processos", credits: 4, code: "EQ3489", semester: 8, category: 1},
    { name: "Economia", credits: 4, code: "EEI312", semester: 9, category: 1},
    { name: "Estágio Obrigatório", credits: 160, code: "EEWU00", semester: 9, category: 1},
    { name: "Projeto de Graduação", credits: 4, code: "EEWX00", semester: 9, category: 1},
    { name: "Atividades Acad. Optativas", credits: 16, semester: 9, step: 1, category: 2},
    { name: "Atividades Acad. Livre Escolha", credits: 8, semester: 9, step: 1, category: 3},
    { name: "Organização das Indústrias", credits: 4, code: "EEI321", semester: 10, category: 1},
    { name: "Atividades Acad. Optativas", credits: 8, semester: 10, step: 1, category: 2},
    { name: "Atividades Acad. Livre Escolha", credits: 8, semester: 10, step: 1, category: 3},
    { name: "Ativ. Compl. Especiais", credits: 405, semester: 10, step: 15, category: 5}
    ]
]
